CREATE TABLE category (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"description" varchar(255) NULL,
	"details" varchar(255) NULL,
	"position" INTEGER NULL,
	CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE product (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"description" varchar(255) NULL,
	"price" varchar(255) NULL,
	"position" INTEGER NULL,
	"category_id" BIGINT NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT category_fkey FOREIGN KEY (category_id) REFERENCES public.category(id)
);

CREATE TABLE public.image (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"url" varchar(255) NOT NULL,
	"public_id" varchar(255) NOT NULL,
	"category_id" BIGINT NULL,
	"product_id" BIGINT NULL,
	CONSTRAINT image_pkey PRIMARY KEY (id),
	CONSTRAINT category_fkey FOREIGN KEY (category_id) REFERENCES public.category(id) ON DELETE CASCADE,
	CONSTRAINT product_fkey FOREIGN KEY (product_id) REFERENCES public.product(id) ON DELETE CASCADE
);